<?php
/**@var Hunters\DistanceSearch\ViewModel\SearchZip $viewModel*/
$viewModel = $this->getData('viewModel');
?>

<div>
    <span class="cord"></span>
</div>


<form action="#" accept-charset="utf-8" method="POST" onSubmit="return false;">
    <input  class="zipsearch" type="search" name="zipjson">
    <input  class="sendZip" type="submit" value="Send">
</form>


<script type="text/javascript">

    require([ 'jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            $(".sendZip").click(function (e) {
                var zip = $(".zipsearch").val();
                var url = "<?php echo $this->getUrl('searchjson/page/ajax', ['_secure' => false]) ?>";
                jQuery.ajax({
                    url: url,
                    type: "POST",
                    data: {
                        zip:zip
                    },
                    showLoader: true,
                    cache: false,
                    complete: function(response) {
                        var res = $.parseJSON(response.responseText);
                        var total = $.parseJSON(res.loc);
                        console.log(total);
                        $(".cord").text("lat = "+total.lat+"; lng = "+total.lng+";");
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });

            });
        });
    });

</script>